"use client";

import { useState } from "react";
import type { GiftAccount } from "@/lib/gifts/schema";

type Draft={id?:string;position:number;label:string;bankId:string;accountNumber:string;accountName:string;confirmed:boolean};
const empty=(position:number):Draft=>({position,label:"",bankId:"",accountNumber:"",accountName:"",confirmed:false});

export function GiftAccountManager({eventId,eventTitle,isPublished,initialAccounts}:{eventId:string;eventTitle:string;isPublished:boolean;initialAccounts:GiftAccount[]}){
  const [accounts,setAccounts]=useState(initialAccounts);const [draft,setDraft]=useState<Draft|null>(null);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  function beginAdd(){const used=new Set(accounts.map((item)=>item.position));setDraft(empty(used.has(1)?2:1));setMessage("")}
  function beginEdit(account:GiftAccount){setDraft({id:account.id,position:account.position,label:account.label,bankId:account.bankId,accountNumber:account.accountNumber,accountName:account.accountName,confirmed:false});setMessage("")}
  async function save(event:React.FormEvent){event.preventDefault();if(!draft)return;setSaving(true);setMessage("");const response=await fetch(`/api/v1/events/${eventId}/gifts`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(draft)});const body=await response.json().catch(()=>null);setSaving(false);if(!response.ok){setMessage(body?.error?.message??"Không thể lưu tài khoản.");return}const saved=body.data as GiftAccount;setAccounts((current)=>[...current.filter((item)=>item.id!==saved.id),saved].sort((a,b)=>a.position-b.position));setDraft(null);setMessage("Đã mã hóa và lưu tài khoản nhận quà.")}
  async function remove(account:GiftAccount){setMessage("");const response=await fetch(`/api/v1/events/${eventId}/gifts/${account.id}`,{method:"DELETE"});const body=await response.json().catch(()=>null);if(!response.ok){setMessage(body?.error?.message??"Không thể xóa tài khoản.");return}setAccounts((current)=>current.filter((item)=>item.id!==account.id));setMessage("Đã xóa tài khoản.")}
  return <main className="shell gift-owner-page"><div className="gift-owner-heading"><div><p className="eyebrow">VietQR · {eventTitle}</p><h1 className="display">Tài khoản nhận quà</h1><p>Lưu tối đa hai người nhận. Khách chỉ thấy tài khoản đã được bạn kiểm tra và xác nhận.</p></div>{accounts.length<2&&!draft&&<button className="button button-primary" onClick={beginAdd} type="button">Thêm người nhận</button>}</div>
    {isPublished&&<div className="gift-security-note"><strong>Thiệp đã xuất bản</strong><span>Để bảo vệ thông tin nhận tiền, phiên đăng nhập phải mới trong 15 phút khi bạn sửa hoặc xóa tài khoản.</span></div>}
    <section className="gift-owner-grid">{accounts.map((account)=><article key={account.id}><div className="gift-owner-card-top"><span>Người nhận {account.position}</span><i>{account.confirmedAt?"Đã xác nhận":"Chưa xác nhận"}</i></div><h2>{account.label}</h2><dl><div><dt>Ngân hàng</dt><dd>{account.bankId}</dd></div><div><dt>Số tài khoản</dt><dd>{account.accountNumber}</dd></div><div><dt>Chủ tài khoản</dt><dd>{account.accountName}</dd></div></dl><div className="gift-owner-actions"><button onClick={()=>beginEdit(account)} type="button">Kiểm tra / sửa</button><button className="danger" onClick={()=>remove(account)} type="button">Xóa</button></div></article>)}{accounts.length===0&&!draft&&<div className="guest-empty">Chưa có tài khoản nhận quà. Phần quà mừng trên thiệp sẽ không mở mã QR cho đến khi bạn thêm và xác nhận.</div>}</section>
    {draft&&<section className="gift-account-editor"><div><p className="eyebrow">{draft.id?"Kiểm tra lại":"Người nhận mới"}</p><h2 className="display">Xác nhận trước khi hiển thị</h2><p>Thông tin dưới đây sẽ được nhúng vào mã VietQR. Hãy đối chiếu chính xác với ứng dụng ngân hàng.</p></div><form onSubmit={save}><div className="editor-two-col"><label><span>Nhãn hiển thị</span><input maxLength={80} placeholder="Cô dâu / Chú rể" required value={draft.label} onChange={(event)=>setDraft({...draft,label:event.target.value})}/></label><label><span>Vị trí</span><select value={draft.position} onChange={(event)=>setDraft({...draft,position:Number(event.target.value)})}><option value="1">Người nhận 1</option><option value="2">Người nhận 2</option></select></label></div><div className="editor-two-col"><label><span>Mã ngân hàng</span><input autoCapitalize="characters" maxLength={12} placeholder="VCB, TCB, MB…" required value={draft.bankId} onChange={(event)=>setDraft({...draft,bankId:event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"")})}/></label><label><span>Số tài khoản</span><input inputMode="numeric" maxLength={19} minLength={6} required value={draft.accountNumber} onChange={(event)=>setDraft({...draft,accountNumber:event.target.value.replace(/\D/g,"")})}/></label></div><label><span>Tên chủ tài khoản</span><input maxLength={120} minLength={2} placeholder="NGUYEN VAN AN" required value={draft.accountName} onChange={(event)=>setDraft({...draft,accountName:event.target.value.toUpperCase()})}/></label><div className="gift-confirm-preview"><small>Xem trước người nhận</small><strong>{draft.bankId||"NGÂN HÀNG"} · {draft.accountNumber||"SỐ TÀI KHOẢN"}</strong><span>{draft.accountName||"TÊN CHỦ TÀI KHOẢN"}</span></div><label className="gift-confirm-check"><input checked={draft.confirmed} onChange={(event)=>setDraft({...draft,confirmed:event.target.checked})} type="checkbox"/><span>Tôi đã kiểm tra ngân hàng, số tài khoản và tên người nhận ở trên.</span></label><div className="gift-editor-actions"><button className="button button-primary" disabled={saving||!draft.confirmed} type="submit">{saving?"Đang mã hóa…":"Xác nhận và lưu"}</button><button className="button button-secondary" onClick={()=>setDraft(null)} type="button">Hủy</button></div></form></section>}
    {message&&<p className="gift-owner-feedback" role="status">{message}</p>}
  </main>;
}
