"use client";

import { FormEvent, useMemo, useState } from "react";
import { filterDashboardGuests, parseDashboardFilters, summarizeDashboard, type DashboardGuest } from "@/lib/rsvp/dashboard";

export function GuestManager({ eventId, publicCode, eventTitle, initialGuests, initialUsed, opens }: { eventId:string;publicCode:string;eventTitle:string;initialGuests:DashboardGuest[];initialUsed:number;opens:number }) {
  const [guests,setGuests]=useState(initialGuests); const [used,setUsed]=useState(initialUsed); const [newLink,setNewLink]=useState<string>();
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [query,setQuery]=useState(""); const [group,setGroup]=useState("");
  const [response,setResponse]=useState("all"); const [delivery,setDelivery]=useState("all");
  const filters=useMemo(()=>parseDashboardFilters({q:query,group,response,delivery}),[query,group,response,delivery]);
  const filtered=useMemo(()=>filterDashboardGuests(guests,filters),[guests,filters]); const summary=useMemo(()=>summarizeDashboard(guests,used),[guests,used]);
  const groups=[...new Set(guests.map((guest)=>guest.group).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"vi"));
  const exportQuery=new URLSearchParams({q:filters.query,group:filters.group,response:filters.response,delivery:filters.delivery}).toString();

  async function createGuest(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const result=await fetch(`/api/v1/events/${eventId}/guests`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({displayName:form.get("displayName"),salutation:form.get("salutation"),guestGroup:form.get("guestGroup"),ownerNote:form.get("ownerNote")})});const payload=await result.json();setBusy(false);if(!result.ok){setMessage(payload.error?.message??"Không thể tạo khách.");return;}setNewLink(`${window.location.origin}${payload.data.invitationPath}`);setUsed((value)=>value+(payload.data.replayed?0:1));setGuests((current)=>[...current,{id:payload.data.guestSlotId,allocationNumber:payload.data.allocationNumber,source:"personalized",displayName:String(form.get("displayName")),salutation:String(form.get("salutation")??""),phone:"",group:String(form.get("guestGroup")??""),ownerNote:String(form.get("ownerNote")??""),sentAt:null,revokedAt:null,createdAt:new Date().toISOString(),response:"pending",companionCount:0,rsvpUpdatedAt:null,wish:"",consentPublicWish:false,moderationStatus:""}]);event.currentTarget.reset();}
  async function rotate(guestId:string){const result=await fetch(`/api/v1/events/${eventId}/guests/${guestId}/rotate`,{method:"POST"});const payload=await result.json();if(result.ok)setNewLink(`${window.location.origin}${payload.data.invitationPath}`);else setMessage(payload.error?.message??"Không thể đổi link.");}
  async function setInvitationState(guestId:string,target:"sent"|"revoked"){const result=await fetch(`/api/v1/events/${eventId}/guests/${guestId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({target})});if(result.ok)setGuests((current)=>current.map((guest)=>guest.id===guestId?{...guest,sentAt:target==="sent"?new Date().toISOString():guest.sentAt,revokedAt:target==="revoked"?new Date().toISOString():guest.revokedAt}:guest));}
  async function moderate(guestId:string,target:"approved"|"hidden"){const result=await fetch(`/api/v1/events/${eventId}/wishes/${guestId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({target})});const payload=await result.json();if(!result.ok){setMessage(payload.error?.message??"Không thể duyệt lời chúc.");return;}setGuests((current)=>current.map((guest)=>guest.id===guestId?{...guest,moderationStatus:target}:guest));}
  async function copy(value:string){await navigator.clipboard.writeText(value);setMessage("Đã sao chép link. Lượt gửi chỉ đổi khi bạn chọn “Đã gửi”.");}

  return <main className="shell guest-page">
    <div className="guest-heading"><div><p className="eyebrow">RSVP Dashboard</p><h1 className="display">{eventTitle}</h1></div><div className="guest-heading-actions"><a className="button button-secondary" href={`/e/${publicCode}`} target="_blank">Mở link chung ↗</a><a className="button button-primary" href={`/api/v1/events/${eventId}/exports/rsvps.xlsx?${exportQuery}`}>Xuất Excel</a></div></div>
    <section className="rsvp-summary-grid"><article><span>Suất đã cấp</span><strong>{summary.allocated}<small>/50</small></strong><p>Không giảm khi thu hồi</p></article><article><span>Đang quản lý</span><strong>{summary.managed}</strong><p>{summary.pending} chưa phản hồi</p></article><article><span>Đồng ý</span><strong>{summary.attending}</strong><p>+{summary.companions} người đi cùng</p></article><article className="summary-featured"><span>Tổng dự kiến</span><strong>{summary.expected}</strong><p>{summary.declined} khách từ chối</p></article><article><span>Lượt mở</span><strong>{opens}</strong><p>Tín hiệu tham khảo</p></article></section>
    <section className="guest-create"><div><p className="eyebrow">Link cá nhân hóa</p><h2 className="display">Thêm một vị khách</h2><p>Tên khách xuất hiện trên phong bì; tạo thành công dùng một suất.</p></div><form onSubmit={createGuest}><div className="rsvp-grid"><label>Tên khách<input name="displayName" required minLength={2} maxLength={100}/></label><label>Cách xưng hô<input name="salutation" maxLength={40} placeholder="Bạn thân, Anh chị…"/></label></div><label>Nhóm khách<input name="guestGroup" maxLength={80} placeholder="Gia đình, đồng nghiệp…"/></label><label>Ghi chú riêng<textarea name="ownerNote" maxLength={1000} rows={2}/></label><button className="button button-primary" disabled={busy||used>=50}>{busy?"Đang tạo…":used>=50?"Đã đủ 50 suất":"Tạo link cá nhân"}</button></form></section>
    {newLink&&<section className="guest-new-link"><div><strong>Link mới chỉ hiển thị trong phiên này</strong><p>{newLink}</p></div><button onClick={()=>copy(newLink)} type="button">Sao chép</button></section>}{message&&<p className="guest-message" role="status">{message}</p>}
    <section className="guest-list"><div className="dashboard-section-heading"><div><p className="eyebrow">Danh sách khách</p><h2 className="display">{filtered.length} kết quả</h2></div><div className="export-links"><a href={`/api/v1/events/${eventId}/exports/rsvps.csv?${exportQuery}`}>CSV UTF-8</a><a href={`/api/v1/events/${eventId}/exports/rsvps.xlsx?${exportQuery}`}>Excel .xlsx</a></div></div>
      <div className="guest-filters"><label>Tìm kiếm<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Tên, nhóm hoặc số điện thoại"/></label><label>Nhóm<select value={group} onChange={(event)=>setGroup(event.target.value)}><option value="">Tất cả nhóm</option>{groups.map((item)=><option key={item}>{item}</option>)}</select></label><label>Phản hồi<select value={response} onChange={(event)=>setResponse(event.target.value)}><option value="all">Tất cả</option><option value="attending">Tham dự</option><option value="declined">Từ chối</option><option value="pending">Chưa phản hồi</option></select></label><label>Gửi thiệp<select value={delivery} onChange={(event)=>setDelivery(event.target.value)}><option value="all">Tất cả</option><option value="sent">Đã gửi</option><option value="unsent">Chưa gửi</option><option value="revoked">Đã thu hồi</option></select></label></div>
      {filtered.length===0?<p className="guest-empty">Không có khách phù hợp với bộ lọc.</p>:<div className="guest-table">{filtered.map((guest)=><article key={guest.id}><div><span>#{guest.allocationNumber} · {guest.source==="personalized"?"Link riêng":"Link chung"}</span><h3>{guest.displayName}</h3><p>{[guest.group,guest.phone].filter(Boolean).join(" · ")||"Chưa có thông tin bổ sung"}</p>{guest.ownerNote&&<small className="owner-note">Ghi chú: {guest.ownerNote}</small>}</div><div className="guest-status"><strong>{guest.response==="attending"?`Tham dự${guest.companionCount?` +${guest.companionCount}`:""}`:guest.response==="declined"?"Từ chối":guest.sentAt?"Đã gửi":"Chưa gửi"}</strong>{guest.revokedAt&&<small>Đã thu hồi</small>}</div>{guest.source==="personalized"&&!guest.revokedAt&&<div className="guest-actions"><button onClick={()=>rotate(guest.id)} type="button">Tạo link mới</button>{!guest.sentAt&&<button onClick={()=>setInvitationState(guest.id,"sent")} type="button">Đã gửi</button>}<button className="danger" onClick={()=>setInvitationState(guest.id,"revoked")} type="button">Thu hồi</button></div>}</article>)}</div>}
    </section>
    <section className="wish-moderation"><div><p className="eyebrow">Lời chúc</p><h2 className="display">Duyệt trước khi công khai</h2><p>Chỉ lời chúc có sự đồng ý của khách mới có thể xuất hiện trên thiệp.</p></div><div>{guests.filter((guest)=>guest.wish).length===0?<p className="guest-empty">Chưa có lời chúc nào.</p>:guests.filter((guest)=>guest.wish).map((guest)=><article key={guest.id}><blockquote>“{guest.wish}”</blockquote><div><strong>{guest.displayName}</strong><span>{!guest.consentPublicWish?"Riêng tư theo lựa chọn của khách":guest.moderationStatus==="approved"?"Đang công khai":guest.moderationStatus==="hidden"?"Đã ẩn":"Chờ duyệt"}</span></div>{guest.consentPublicWish&&<div className="guest-actions"><button disabled={guest.moderationStatus==="approved"} onClick={()=>moderate(guest.id,"approved")}>Duyệt</button><button className="danger" disabled={guest.moderationStatus==="hidden"} onClick={()=>moderate(guest.id,"hidden")}>Ẩn</button></div>}</article>)}</div></section>
  </main>;
}
